# Generated by Django 4.1.3 on 2023-02-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_order_options_alter_staff_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='group',
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Фото пользователя'),
        ),
    ]
