# Generated by Django 4.1.3 on 2023-02-19 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_staff_group_alter_user_patronymic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='group',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.staff'),
            preserve_default=False,
        ),
    ]
